### ISSUE TITLE
Error after searching for title

### ISSUE THREAD

**Issue by booYah187** [shreyashchavan/Privateer#1]
After entering search term for movie title I receive the following before returning to shell:

Traceback (most recent call last):
  File "./Downloads/as.py", line 135, in <module>
    main()
  File "./Downloads/as.py", line 58, in main
    Movie()
  File "./Downloads/as.py", line 77, in Movie
    if 'movie' in results['type'].lower():
TypeError: string indices must be integers

Periodically it functions as expected, but the majority of the time I receive the above error. The search term itself does not seem to matter, the same query will error out and then later return results, with no difference in how it is entered. Same results experienced on Xubuntu 21.04, GalliumOS, and TwisterOS.

**Comment by shreyashchavan** [comment]
Thank you for reaching out to me. I will definitely try to resolve it.

Thank you for your time.
